### ISSUE TITLE
Grundpaket: Epic Basissystem für EJV

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_ejv#1]
Ziel: Aufbau Grundpaket/Umgebung für die KUNDE

Inhalt:

- [x] Neues Repo erstellen: hitobito_kunde About ergänzen
- [x] Wagon erstellen #4 
- [x] Setup der Integrationsumgebung #2 
- [x] Gruppenstruktur, Rollen, Berechtigungen #5 
- [x] Visuelle Anpassungen #6 
- [x] Resourcen bestellen bei /sys
- [x] Mehrsprachigkeit #7 
- [x] Produktionsumgebung #3 
- [x] Github Actions
- [x] DNS Einstellungen Kundenseite
- [x] Wartung und Support
